### ISSUE TITLE
クラス名の変更

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/DamageText#2]
https://github.com/nkc20206082/DamageText/blob/1e03d0195227de0cf1b4df84acf2d3b3668bb345/AttackController.cs#L3

`AttackController`はプレイヤーのクラス名だったり敵に付けそうで複数同じクラス名を生み出しそうで怖いから変えてほしい。
意味的にも攻撃管理をするスクリプトじゃないからクラス名として不適切だと思う。
`DamageTextMaker`とかどうだろう

**Comment by nkc20206082** [comment]
TextMakerに変更

**Comment by ayaha401** [comment]
終わってるので閉じるね
