### ISSUE TITLE
スクリプト全体について

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/DamageText#3]
![image](https://user-images.githubusercontent.com/75297336/159437381-05e22037-7797-4ac0-813e-1b4386b965a3.png)
現状システムがこんな感じになっていて、敵が1体1体全員がこの作業をしてる。
これだと効率が悪くて
* 敵1体1体全員にAttackControllerというスクリプトがくっついてて無駄

みんなが同じ動作（オブジェクトの下に非アクティブなオブジェクトがあるか探す）をするのならば1つだけスクリプトを置いておいて、みんな使ってねって方式にしたほうがスクリプトの枚数が減る。

今は
自分(敵)がダメージを受けたら`自力でオブジェクトを検索`して`自力でテキストを生成`するシステム
になってるこれを
自分がダメージを受けたら`オブジェクトを検索する機能`を使って`テキストを生成`してもらう
っていうシステムに作り替えればいい

**Comment by nkc20206082** [comment]
敵がテキストメーカーへトランスフォーム情報を送って、テキストメーカーを保持した別オブジェクトが受け取ったトランスフォーム情報をもとにテキストの生成、プールをするようにしました。

**Comment by ayaha401** [comment]
https://github.com/nkc20206082/DamageText/blob/ce54261ac5a04e84f858a79fa6ea8a2825c9453c/TextMaker.cs#L8
たぶんいい感じだけどここを治すべき
https://github.com/nkc20206082/DamageText/blob/ce54261ac5a04e84f858a79fa6ea8a2825c9453c/TextMaker.cs#L23
ここに座標と回転を入れるために`Transform`を引数としてるんだろうけど`Transform`だと情報量が多いからもっと絞って、引数を2つにして`Vecter3`のpositionと`Vecter3`の回転にするべき

**Comment by nkc20206082** [comment]
直して、敵から当たった回数を送りテキストを変更する処理を追加しました

**Comment by ayaha401** [comment]
スクリプト全体に対していうことはもうない気がするから閉じるね
