### ISSUE TITLE
回転を決める必要性があるのか考えよう

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/DamageText#4]
https://github.com/nkc20206082/DamageText/blob/32482b7ae3e7840f4b0306f5f3cbdb9953344b4d/TextMaker.cs#L8
ここの`TargetRot`で回転を取得してるのに

https://github.com/nkc20206082/DamageText/blob/32482b7ae3e7840f4b0306f5f3cbdb9953344b4d/TextMaker.cs#L23
ここのオブジェクトが足りなくて生成する時は`Instantiate()`で`TargetRot`の回転、

https://github.com/nkc20206082/DamageText/blob/32482b7ae3e7840f4b0306f5f3cbdb9953344b4d/TextMaker.cs#L28
逆にオブジェクトが足りててアクティブ状態を切り替えるときは`Quaternion.identity`(無回転)になってる

`Quaternion.identity`(無回転)でいいなら引数の`TargetRot`はいらないし、今後回転を決める必要性があるのならば
https://github.com/nkc20206082/DamageText/blob/32482b7ae3e7840f4b0306f5f3cbdb9953344b4d/TextMaker.cs#L28
ここの`Quaternion.identity`(無回転)を`TargetRot`回転できるように修正しないといけない

**Comment by nkc20206082** [comment]
無回転にした

**Comment by ayaha401** [comment]
いい感じ！閉じますね
