### ISSUE TITLE
引数の名前小文字から初めていいと思う

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/DamageText#5]
https://github.com/nkc20206082/DamageText/blob/32482b7ae3e7840f4b0306f5f3cbdb9953344b4d/TextMaker.cs#L8
ここの`TargetPos`、`TargetRot` 、`Num`は小文字から初めて欲しい

下の命名規則についてのサイトに目を通してほしい、読むべき該当場所に飛べるリンクにしておいたので。

参考  :  [命名規則についてのサイト](http://www.kanazawa-net.ne.jp/~pmansato/vs/vs_codingstyle.htm#:~:text=%E3%81%AE%E4%BB%98%E3%81%91%E6%96%B9%E3%81%A7%E3%81%99%E3%80%82-,Pascal%20%E5%BD%A2%E5%BC%8F%E3%81%A8%20Camel%20%E5%BD%A2%E5%BC%8F,-%E4%BC%9D%E7%B5%B1%E7%9A%84%E3%81%AA)

まとめると
* クラス名、プロパティ名、メソッド名では大文字スタート
* ローカル変数やメソッドの引数の変数名では小文字スタート

**Comment by nkc20206082** [comment]
小文字にした

**Comment by ayaha401** [comment]
いい感じ。閉じますね
